### ISSUE TITLE
Separator characters look off

### ISSUE THREAD

**Issue by joshnesbitt** [MrRio/vtop#2]
Not sure if this is because the font you're using is missing on my machine, but the dividers look different?

![screen shot 2014-06-09 at 09 56 38](https://cloud.githubusercontent.com/assets/33054/3214706/2ff194b6-efb4-11e3-846f-45f2c8004dc8.png)

**Comment by rdebath** [comment]
This is due to the use of the "alternate character set" by your terminal driver library. 
This is a holdover from the VT100 (Introduced in 1978) which only had a 7bit terminal interface.
To get around this they invented an alternate character scheme which eventually became `ISO2022` (aka ECMA35). This is a horrific standard that nobody likes but the Japanese were basically forced to use as it was the only way to use their native language. 

The additional characters that the VT100 provided where these:
`♦▒␉␌␍␊°±␤␋┘┐┌└┼⎺⎻─⎼⎽├┤┴┬│≤≥π≠£· `
They all exist in the Unicode standard today (as you can see) and if the terminal is Unicode the Unicode characters should be used in preference. Some terminals enforce this and disable the all the archaic ISO2022 sequences in UTF-8 mode (as ISO2022 says they should).

Note in addition to the box drawing characters these `⎺⎻─⎼⎽` five should be equally spaced up the character cell so you can make 80x125 graphs ... sound familiar?

This should be a 'straight line' with no larger, or smaller, gaps.
```
⎺⎻─⎼⎽
     ⎺⎻─⎼⎽
```
